#!/bin/sh
if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
    echo "Commit theo chuẩn Conventional Commits nhé!!!" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,255}$"; then
    echo "Commit ngắn lại đi fen ơi dài quá rồi, đọc nhiều lú không hiểu đâu!!!" >&2
    exit 1
fi